"""Schema 6: canonical AST with unit-local interned strings and compact IDs."""
STATEMENTS=(
 '''CREATE TABLE k2_ast_units(unit_id INTEGER PRIMARY KEY REFERENCES k2_units ON DELETE CASCADE,
    version TEXT NOT NULL, diagnostics TEXT NOT NULL)''',
 '''CREATE TABLE k2_ast_strings(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    string_id INTEGER NOT NULL, value TEXT NOT NULL, PRIMARY KEY(unit_id,string_id), UNIQUE(unit_id,value)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_string_value ON k2_ast_strings(value,unit_id,string_id)',
 '''CREATE TABLE k2_ast_nodes(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    node_id INTEGER NOT NULL, parent INTEGER, ordinal INTEGER NOT NULL, scope INTEGER NOT NULL,
    kind INTEGER NOT NULL, category INTEGER NOT NULL, name INTEGER NOT NULL,
    start_byte INTEGER NOT NULL,end_byte INTEGER NOT NULL,subtree_end INTEGER NOT NULL,
    data TEXT NOT NULL,PRIMARY KEY(unit_id,node_id)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_node_kind ON k2_ast_nodes(unit_id,kind,node_id)',
 'CREATE INDEX k2_ast_node_name ON k2_ast_nodes(unit_id,name,kind,node_id)',
 'CREATE INDEX k2_ast_node_parent ON k2_ast_nodes(unit_id,parent,ordinal)',
 'CREATE INDEX k2_ast_node_scope ON k2_ast_nodes(unit_id,scope,kind,node_id)',
 '''CREATE TABLE k2_ast_scopes(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    scope_id INTEGER NOT NULL,parent INTEGER,node_id INTEGER NOT NULL,namespace INTEGER NOT NULL,
    data TEXT NOT NULL,PRIMARY KEY(unit_id,scope_id)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_scope_namespace ON k2_ast_scopes(unit_id,namespace,scope_id)',
 '''CREATE TABLE k2_ast_symbols(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    symbol_id INTEGER NOT NULL,scope INTEGER NOT NULL,name INTEGER NOT NULL,declaration INTEGER NOT NULL,
    visible_from INTEGER NOT NULL,data TEXT NOT NULL,PRIMARY KEY(unit_id,symbol_id)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_symbol_lookup ON k2_ast_symbols(unit_id,scope,name,visible_from)',
 '''CREATE TABLE k2_ast_references(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    node_id INTEGER NOT NULL,symbol INTEGER,scope INTEGER NOT NULL,name INTEGER NOT NULL,
    data TEXT NOT NULL,PRIMARY KEY(unit_id,node_id)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_reference_symbol ON k2_ast_references(unit_id,symbol,node_id)',
 '''CREATE TABLE k2_ast_links(unit_id INTEGER NOT NULL REFERENCES k2_ast_units ON DELETE CASCADE,
    source INTEGER NOT NULL,relation TEXT NOT NULL,target INTEGER NOT NULL,ordinal INTEGER NOT NULL,
    PRIMARY KEY(unit_id,source,relation,target,ordinal)) WITHOUT ROWID''',
 'CREATE INDEX k2_ast_link_target ON k2_ast_links(unit_id,relation,target,source)',
)
TABLES=('k2_ast_links','k2_ast_references','k2_ast_symbols','k2_ast_scopes','k2_ast_nodes','k2_ast_strings','k2_ast_units')
