//! End-to-end retrieval quality test on a small handcrafted corpus, using
//! real fastembed embeddings + real Postgres + the full ranker. This is the
//! integration-level regression guard for retrieval quality (cf. infinidev's
//! `test_context_rank_benchmark.py`).
//!
//! Each query asserts a specific expected chunk surfaces in top-K. Tests are
//! split per query so a regression points at exactly which scenario broke
//! (vs. one monolithic test reporting "4/6 passed"). A query-level hit-rate
//! sanity check is bundled at the end.
//!
//! Why a tiny corpus (10 chunks): with real embeddings and the default
//! confidence gate we only need a handful of chunks for the test to be
//! informative — adding noise chunks doesn't change the calibration story
//! and only inflates test time. The synthetic ranker test in
//! `ranker_quality.rs` is the place to test merge / MAD shape; this file
//! is the place to test calibration.
//!
//! Run with:
//!     DATABASE_URL=postgres://cae:cae_dev@localhost:5432/context_engine \
//!     cargo test -p cae-engine --features "postgres fastembed" \
//!         --test end_to_end_quality -- --ignored

#![cfg(all(feature = "postgres", feature = "fastembed"))]

use engine::embed::Embedder;
use engine::embed_fast::FastEmbedder;
use engine::postgres::PostgresStorage;
use engine::rank::{RankRequest, Ranker, RankResult};
use engine::storage::{NewChunk, NewDocument, NewSource};
use engine::types::*;

/// Minimal corpus — each entry becomes a document with one chunk. Slug is
/// the external_id we'll use to identify the chunk after ranking.
const CORPUS: &[(&str, &str)] = &[
    (
        "auth-jwt",
        "Authentication uses JWT tokens. Tokens are issued on login \
         and validated on every API request via the auth middleware.",
    ),
    (
        "auth-rotation",
        "JWT tokens rotate every 30 minutes. The refresh endpoint \
         exchanges an expiring access token for a new one without \
         requiring the user to re-enter credentials.",
    ),
    (
        "billing-stripe",
        "Billing is handled by Stripe. We create subscription objects \
         on plan upgrade and listen for webhook events to update local \
         tenant state.",
    ),
    (
        "kubernetes-deploy",
        "Production runs on a Kubernetes cluster with three replicas \
         per service. Deployments use rolling updates with a 30-second \
         readiness probe.",
    ),
    (
        "rate-limiting",
        "Rate limiting is implemented per user with a sliding-window \
         counter stored in Redis. The limit is 100 requests per minute \
         and returns 429 on exceed.",
    ),
    (
        "ml-embedding",
        "Document embeddings are generated by nomic-embed-text-v1.5, a \
         768-dimensional sentence encoder. Vectors are stored in pgvector \
         and queried via HNSW indexes.",
    ),
    (
        "search-ranking",
        "Search results are ranked by a multi-channel scorer combining \
         reactive session signals, predictive knowledge-graph hops, and \
         semantic cosine similarity.",
    ),
    (
        "infra-terraform",
        "Infrastructure is managed by Terraform modules. The AWS VPC, \
         subnets, and IAM roles are versioned in a separate platform repo.",
    ),
    (
        "team-pumpkin",
        "Our team's office mascot is an orange cat named Pumpkin. He \
         spends most of the day napping next to the espresso machine.",
    ),
    (
        "lunch-pasta",
        "On Fridays the team orders pasta from the trattoria across the \
         street. The carbonara is excellent; the gnocchi is divisive.",
    ),
];

/// Each entry: (test_name, query, expected_slug, secondary_acceptable).
/// `secondary_acceptable` lists slugs that are also reasonable matches.
/// We pass when the expected slug appears in top-K, OR when one of the
/// acceptable alternatives does (calibration is allowed to disagree on
/// near-ties as long as the answer remains topical).
const QUERIES: &[(&str, &str, &str, &[&str])] = &[
    (
        "q1_exact_concept_jwt",
        "how does jwt authentication work in this codebase",
        "auth-jwt",
        &["auth-rotation"],
    ),
    (
        "q2_paraphrase_token_refresh",
        "how do we refresh expired access tokens without re-login",
        "auth-rotation",
        &["auth-jwt"],
    ),
    (
        "q3_concept_ratelimit",
        "what's the policy for limiting request volume per user",
        "rate-limiting",
        &[],
    ),
    (
        "q4_paraphrase_kubernetes",
        "where is our production environment hosted and how is it scaled",
        "kubernetes-deploy",
        &[],
    ),
    (
        "q5_descriptive_embedding",
        "which model produces the document vectors",
        "ml-embedding",
        &[],
    ),
    (
        "q6_concept_payment_processing",
        "how do we process customer payments and subscriptions",
        "billing-stripe",
        &[],
    ),
];

async fn setup() -> Option<(PostgresStorage, WorkspaceId, Vec<(String, ChunkId)>)> {
    let url = std::env::var("DATABASE_URL").ok()?;
    let s = PostgresStorage::connect(&url).await.expect("connect");
    s.migrate().await.expect("migrate");
    let t = s
        .create_tenant("e2e-quality", PlanTier::Free)
        .await
        .expect("tenant");
    let w = s
        .create_workspace(t, "ws", WorkspaceSettings::default())
        .await
        .expect("workspace");
    let src = s
        .create_source(NewSource {
            workspace_id: w,
            kind: SourceKind::Manual,
            name: "manual".into(),
            config_json: serde_json::Value::Null,
            keep_history: false,
            default_acl: Acl::default(),
        })
        .await
        .expect("source");

    let embedder = FastEmbedder::nomic_v15().expect("fastembed init");
    let mut by_slug: Vec<(String, ChunkId)> = Vec::with_capacity(CORPUS.len());

    // Batch-embed all passages once — fastembed amortizes much better than
    // single calls because the ONNX session reuses input buffers.
    let passages: Vec<&str> = CORPUS.iter().map(|(_, p)| *p).collect();
    let vectors = embedder.embed_passages(&passages);
    assert_eq!(vectors.len(), CORPUS.len());

    for ((slug, text), vec) in CORPUS.iter().zip(vectors.into_iter()) {
        let did = s
            .upsert_document(NewDocument {
                workspace_id: w,
                source_id: src,
                external_id: Some((*slug).to_string()),
                kind: ContentKind::PlainText,
                mime: "text/plain".into(),
                title: Some((*slug).to_string()),
                path_or_url: None,
                content_hash: *blake3::hash(text.as_bytes()).as_bytes(),
                acl: Acl::default(),
                metadata: MetadataMap::default(),
                source_modified_at: None,
            })
            .await
            .unwrap()
            .current_id();
        let cids = s
            .replace_chunks(
                did,
                vec![NewChunk {
                    kind: ChunkKind::Paragraph,
                    position: ChunkPosition::ByteRange { start: 0, end: text.len() as u64 },
                    text: (*text).to_string(),
                    metadata: MetadataMap::default(),
                    embedding: None,
                }],
            )
            .await
            .unwrap();
        s.put_embedding(EmbedKey::chunk(cids[0]), vec).await.unwrap();
        by_slug.push(((*slug).to_string(), cids[0]));
    }
    Some((s, w, by_slug))
}

fn slug_for(by_slug: &[(String, ChunkId)], cid: ChunkId) -> Option<&str> {
    by_slug.iter().find(|(_, c)| *c == cid).map(|(s, _)| s.as_str())
}

fn fmt_topk(by_slug: &[(String, ChunkId)], result: &RankResult, k: usize) -> Vec<String> {
    result
        .items
        .iter()
        .take(k)
        .map(|it| {
            let label = match it.target {
                NodeRef::Chunk(c) => slug_for(by_slug, c).unwrap_or("?").to_string(),
                _ => format!("{:?}", it.target),
            };
            format!("{label}@{:.2}({})", it.score, it.reason)
        })
        .collect()
}

async fn run_query(
    s: &PostgresStorage,
    w: WorkspaceId,
    embedder: &FastEmbedder,
    query: &str,
) -> RankResult {
    let session = s.create_session(w, Some("e2e-quality")).await.unwrap();
    let ranker = Ranker::new(s);
    ranker
        .rank(RankRequest {
            workspace: w,
            session,
            query_embedding: embedder.embed_query(query),
            iteration: 0,
        })
        .await
}

fn topk_contains(
    result: &RankResult,
    by_slug: &[(String, ChunkId)],
    expected: &str,
    acceptable: &[&str],
    k: usize,
) -> bool {
    result.items.iter().take(k).any(|it| {
        if let NodeRef::Chunk(c) = it.target {
            let slug = slug_for(by_slug, c).unwrap_or("?");
            slug == expected || acceptable.contains(&slug)
        } else {
            false
        }
    })
}

// ============================================================================
// Per-query tests — each one is a mini regression guard.
// ============================================================================

const TOP_K: usize = 3;

async fn check_one_query(idx: usize) {
    let Some((s, w, by_slug)) = setup().await else { return };
    let embedder = FastEmbedder::nomic_v15().expect("fastembed init");
    let (name, query, expected, acceptable) = QUERIES[idx];
    let result = run_query(&s, w, &embedder, query).await;
    assert!(
        topk_contains(&result, &by_slug, expected, acceptable, TOP_K),
        "{name}: query={query:?} expected={expected:?} acceptable={acceptable:?}; \
         top-{TOP_K} = {:?}",
        fmt_topk(&by_slug, &result, TOP_K)
    );
}

#[tokio::test]
#[ignore]
async fn q1_exact_concept_jwt() {
    check_one_query(0).await;
}

#[tokio::test]
#[ignore]
async fn q2_paraphrase_token_refresh() {
    check_one_query(1).await;
}

#[tokio::test]
#[ignore]
async fn q3_concept_ratelimit() {
    check_one_query(2).await;
}

#[tokio::test]
#[ignore]
async fn q4_paraphrase_kubernetes() {
    check_one_query(3).await;
}

#[tokio::test]
#[ignore]
async fn q5_descriptive_embedding() {
    check_one_query(4).await;
}

#[tokio::test]
#[ignore]
async fn q6_concept_payment_processing() {
    check_one_query(5).await;
}

// ============================================================================
// Negative test: unrelated query should be filtered by the confidence gate.
// ============================================================================

#[tokio::test]
#[ignore]
async fn unrelated_query_is_rejected_by_confidence_gate() {
    let Some((s, w, by_slug)) = setup().await else { return };
    let embedder = FastEmbedder::nomic_v15().expect("fastembed init");
    let result = run_query(
        &s,
        w,
        &embedder,
        "what is the chemical composition of saturn's atmosphere",
    )
    .await;
    // Either empty (gate fired), OR every top-K item is below 0.5 cosine.
    // The gate's job is to prevent confident-looking nonsense — if it fired
    // we're done; if it didn't, the items must at least not be high-confidence.
    if !result.items.is_empty() {
        assert!(
            result.items[0].score < 0.5,
            "expected gate to reject or low confidence; got top {:?}",
            fmt_topk(&by_slug, &result, TOP_K)
        );
    }
}

// ============================================================================
// Aggregate hit-rate.
// ============================================================================

#[tokio::test]
#[ignore]
async fn aggregate_hit_rate_at_least_5_of_6() {
    let Some((s, w, by_slug)) = setup().await else { return };
    let embedder = FastEmbedder::nomic_v15().expect("fastembed init");
    let mut hits = 0usize;
    let mut report: Vec<String> = Vec::new();
    for (name, query, expected, acceptable) in QUERIES {
        let result = run_query(&s, w, &embedder, query).await;
        let ok = topk_contains(&result, &by_slug, expected, acceptable, TOP_K);
        if ok {
            hits += 1;
        } else {
            report.push(format!(
                "{name}: query={query:?} expected={expected:?} top={:?}",
                fmt_topk(&by_slug, &result, TOP_K)
            ));
        }
    }
    assert!(
        hits >= QUERIES.len() - 1,
        "hit-rate {hits}/{} (≥{} required); misses:\n{}",
        QUERIES.len(),
        QUERIES.len() - 1,
        report.join("\n")
    );
}
